//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Referrals.ReferralsServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommMethod
    {
        public CommMethod()
        {
            this.Communications = new HashSet<Communication>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Communication> Communications { get; set; }
    }
}
