//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Referrals.ReferralsServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communication
    {
        public int Id { get; set; }
        public Nullable<int> CommMethodId { get; set; }
        public int ActionId { get; set; }
        public int FromAcctId { get; set; }
        public int ToAcctId { get; set; }
        public Nullable<int> ReferredAcctId { get; set; }
        public Nullable<int> JobId { get; set; }
        public int StatusToId { get; set; }
        public int StatusReferredId { get; set; }
        public Nullable<System.Guid> ReferralId { get; set; }
        public Nullable<System.Guid> ConversationId { get; set; }
        public string SubjectTo { get; set; }
        public string MessageTo { get; set; }
        public string MessageToEmail { get; set; }
        public string MessageToTxtMsg { get; set; }
        public string SubjectReferred { get; set; }
        public string MessageReferred { get; set; }
        public string MessageReferredEmail { get; set; }
        public string MessageReferredTxtMsg { get; set; }
        public Nullable<bool> MessageToEmailSent { get; set; }
        public Nullable<bool> MessageToTxtMsgSent { get; set; }
        public Nullable<bool> MessageRefEmailSent { get; set; }
        public Nullable<bool> MessageRefTxtMsgSent { get; set; }
        public Nullable<bool> Archived { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string LastUpdatedBy { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Account Account2 { get; set; }
        public virtual Action Action { get; set; }
        public virtual CommMethod CommMethod { get; set; }
        public virtual Job Job { get; set; }
        public virtual Status Status { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
