//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Referrals.ReferralsServices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReferralsEntities : DbContext
    {
        public ReferralsEntities()
            : base("name=ReferralsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<AccountContact> AccountContacts { get; set; }
        public DbSet<AccountLocation> AccountLocations { get; set; }
        public DbSet<AccountProfession> AccountProfessions { get; set; }
        public DbSet<Action> Actions { get; set; }
        public DbSet<CommMethod> CommMethods { get; set; }
        public DbSet<Communication> Communications { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Job> Jobs { get; set; }
        public DbSet<Profession> Professions { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<Status> Status { get; set; }
    }
}
